[configs]
OnlyHorzOnOtherWeapons = 0
OnlyHorzInSniper = 0

; AimForTheCam v1.0
[PT]
; OnlyHorzOnOtherWeapons || 0 = desativado | 1 = ativado
; Habilite essa opção para que o mod funcione apenas horizontalmente em todas as armas exceto na sniper

; OnlyHorzInSniper || 0 = desativado | 1 = ativado 
; Mesmo principio da opção anterior, mas apenas na sniper

; Se você não entendeu, basicamente essas opções fazem com que não seja possivel mirar para cima ou para baixo com esse mod.

; Mod criado por KillerSA e Yuna
; Discords: _killer#6467 | Yuna#5433
; Não remova esses créditos!!!


[ENG]
; OnlyHorzOnOtherWeapons || 0 = disabled | 1 = activated
; Enable this option so that the mod only works horizontally on all weapons except the sniper

; OnlyHorzInSniper || 0 = disabled | 1 = activated
; The same principle as the previous option, but only in sniper

; If you don't understand, basically these options make it not possible to aim up or down with this mod.

; Mod created by KillerSA and Yuna
; Discords: _killer#6467 | Yuna#5433
; Do not remove these credits!!!

; Ultragaz Mods - https://discord.gg/tY2bffCxax